filebeat.inputs:
  # Exclure anaconda de input all pour ne pas avoir de doublon
- type: log
  paths:
    - /var/log/*.log
  exclude_files: [ 'anaconda.*\.log' ]
  
  # Anaconda log 
  # supporte les fichiers anaconda(\.(storage|program))?\.log
  # non supporté anaconda.syslog, anaconda.xlog anaconda.yum.log
- type: log
  paths: /var/log/anaconda*.log
  multiline.pattern: '^([0-1]?\d|2[0-3])(:[0-5]\d){2},\d{3}\s'
  multiline.negate: true
  multiline.match: after
  tags: ["anaconda_old"]

# I like regex xD